token="xxxxxxxxxx"
pool_addresses = []
test_pool_addresses= ["pool.nlb.staging.dmnd.work:20000", "18.193.252.132:2000", "3.74.36.119:2000"]
tp_address = "127.0.0.1:8442"
interval = 120_000
delay = 540
downstream_hashrate = "100T"
loglevel = "info"
nc_loglevel = "off"
test = true
